version: '2'
services:
    ggstat-app:
        image: ggstat
        external_links:
            - ggstat-mysql:mysql
            - ggstat-elasticsearch:elasticsearch
            - kafka:kafka
            - zookeeper:zookeeper
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/ggstat?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=elasticsearch:9300
            - SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS=kafka
            - SPRING_CLOUD_STREAM_KAFKA_BINDER_ZK_NODES=zookeeper
        ports:
            - 8080:8080
    ggstat-mysql:
        extends:
            file: mysql.yml
            service: ggstat-mysql
    ggstat-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: ggstat-elasticsearch
    kafka:
        extends:
            file: kafka.yml
            service: kafka
        environment:
            - KAFKA_ADVERTISED_HOST_NAME=kafka
    zookeeper:
        extends:
            file: kafka.yml
            service: zookeeper
